### ISSUE TITLE
Feedback round 2 (by Helge Jacobsen)

### ISSUE THREAD

**Issue by elgehelge** [madsbf/cv-kickstarter#1]
Extremely well written code, divided into small meaningful and self explanatory functions/methods/classes.

Extremely well written and extensive testing.

Even though the code is very self explanatory you should add docstrings.

At this point, put some energy in making a killer presentation that points out why this is advanced data mining.

**Comment by anderslime** [comment]
Hey Helge,

Thank you for the feedback. We will put the rest of the effort in explaining our Data Mining in the presentation and report and adding docstrings.

Btw. Feel free to contribute :wink:
